stages:
  - build
  - publish

variables:
  DOCKER_REGISTRY: "192.168.10.110:8624"

image: "${DOCKER_REGISTRY}/puya-docker-registry/node-git"

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run clean
    - npm run build 
  artifacts:
    paths:
      - bin/

publish:
  stage: publish
  script:
    - cat <<EOF > ~/.npmrc
    - registry=http://192.168.10.110:8624/npm/private-npm/
    - //192.168.10.110:8624/npm/private-npm/:_authToken=${NPM_AUTH_TOKEN}
    - EOF
    - npm config set registry http://192.168.10.110:8624/npm/private-npm/
    - npm config set _auth "${NPM_AUTH_TOKEN}"
    - npm pkg fix
    - npm publish --verbose
  only:
    - dev