stages:
  - build
  - publish

variables:
  DOCKER_REGISTRY: "192.168.10.110:8624"
  NPM_REGISTRY: "192.168.10.110:8624/npm/private-npm/"

image: "${DOCKER_REGISTRY}/puya-docker-registry/node-git"

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run clean
    - npm run build 
  artifacts:
    paths:
      - bin/

publish:
  stage: publish
  script:
    - echo "//${NPM_REGISTRY}:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
    - cat .npmrc
    - npm pkg fix
    - npm publish --registry=http://${NPM_REGISTRY}
  only:
    - dev